### ISSUE TITLE
Resource temporarily unavailable - ./node_modules/.bin/playwright run-driver

### ISSUE THREAD

**Issue by goldenking0412** [YusukeIwaki/playwright-ruby-client#105]
I am running playwright scraper in windows. About 5 scraping requests at once.
Did ``npm install playwright`` to install playwright in windows

And it works at first.
But after a few mins or few requests, I am getting error 
```Resource temporarily unavailable - ./node_modules/.bin/playwright run-driver```

Can you please check what's wrong with this?

**Comment by YusukeIwaki** [comment]
Could you share the summary of the scraping code?
I guess `Playwright.create` is repeatedly called and the Windows process limit is exceeded, but I can't check it in detail without how Playwright is used in your code.

**Comment by goldenking0412** [comment]
Can you please give me your email?
I dont want to reveal the code to everyone.
Would like to give code via email

**Comment by goldenking0412** [comment]
And also I have a question, How can I use chrome extension? I can not find document in this gem

**Comment by YusukeIwaki** [comment]
The error doesn't occur if `Playwright.create` is called with block or properly used with `PlaywrightExecution#stop`
Too many Playwright sessions are generated for causing the error.

**Comment by goldenking0412** [comment]
```
    Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
      playwright.chromium.launch(headless: false) do |browser|
        page = browser.new_page

        page.goto url
        
        scrape page
      end
    end
```
Here's summary code.
