### ISSUE TITLE
why extensions are super important

### ISSUE THREAD

**Issue by udiudiudiudi** [YusukeIwaki/playwright-ruby-client#110]
if you want to run stealth, then extensions are key, among them noscript and adsblocker.
so having an option to implement extensions on the browser is a must

https://digiwonk.gadgethacks.com/how-to/canvas-fingerprinting-stop-webs-sneakiest-tracking-tool-your-browser-0156506/

can you implement this please?

**Comment by udiudiudiudi** [comment]
this extension blocks canvas fingerprinting - https://chrome.google.com/webstore/detail/canvas-blocker-fingerprin/nomnklagbgmgghhjidfhnoelnjfndfpd?hl=en

**Comment by udiudiudiudi** [comment]
3.5% of the websites use canvas fingerprint - https://www.reddit.com/r/privacy/comments/gtu6uc/how_do_i_get_my_webgl_vendor_renderer_to_be_less/

**Comment by YusukeIwaki** [comment]
I understand the use-case, but I have a question about the environment.
Could you tell me why the function is used with Ruby?

We can already use such feature with TypeScript, as is documented here. https://github.com/microsoft/playwright/blob/1479610abdecc4be3efc095034eaf7853f739b48/docs/src/chrome-extensions.md
I thought Chrome extension testing is rarely used with Ruby (but often used with JavaScript), and decided not to implement BackgroundPage soon in playwright-ruby-client.

**Comment by udiudiudiudi** [comment]
I prefer extensions, but if you can implement the truescript that will also be good for me, thank you in advance

**Comment by YusukeIwaki** [comment]
Are you Ruby user?

**Comment by udiudiudiudi** [comment]
Yes

**Comment by goldenking0412** [comment]
@YusukeIwaki I need this chrome extension feature and will be happy if it's implemented

**Comment by udiudiudiudi** [comment]
here is another use case, useragent switcher - chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

**Comment by YusukeIwaki** [comment]
Why not use official JavaScript or Python version of Playwright?

**Comment by goldenking0412** [comment]
We already started scraping development with ruby.

**Comment by YusukeIwaki** [comment]
Essentially dup of #104.
Documentation is already updated: https://playwright-ruby-client.vercel.app/docs/article/guides/semi_automation#working-with-chrome-extensions
