### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by goldenking0412** [YusukeIwaki/playwright-ruby-client#113]
@YusukeIwaki 
```
    Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
      playwright.chromium.launch(headless: false) do |browser|
        page = browser.new_page

        page.goto url
        
        scrape page
      end
    end
```
Here's summary code.
Do I need to add ``begin...rescue`` there?

_Originally posted by @goldenking0412 in https://github.com/YusukeIwaki/playwright-ruby-client/issues/105#issuecomment-859213641_

**Comment by YusukeIwaki** [comment]
I can't afford to support with such limited information.
