### ISSUE TITLE
launch_persistent_context opens 2 tabs

### ISSUE THREAD

**Issue by goldenking0412** [YusukeIwaki/playwright-ruby-client#115]
I use ``launch_persistent_context`` method and it opens 2 tabs.
First tab showing automation and the scraper is running on second tab.

Is it a bug?

![image](https://user-images.githubusercontent.com/41209214/121797903-bec80c80-cc55-11eb-8a4d-3d9ae0ef97c1.png)

**Comment by YusukeIwaki** [comment]
playwright-python also opens 2 tabs. The behavior is not caused by each client (playwright-ruby-client or playwright-python), but caused by Playwright driver.
Could you plase ask it in https://github.com/microsoft/playwright/issues if the problem is serious for your use case?


> First tab showing automation and the scraper is running on second tab.

This behavior is not observed in my example. Is the issue reproduced in your environment with the code below?

```ruby
require 'playwright'

Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch_persistent_context('./data/', channel: 'chrome', headless: false) do |context|
    page = context.new_page
    page.goto('https://github.com/YusukeIwaki')
    page.click('input[name="q"]')
    page.keyboard.type('playwright')
    page.expect_navigation do
      page.keyboard.press('Enter')
    end
    puts page.url
  end
end
```

**Comment by goldenking0412** [comment]
```ruby
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
    launch_param = {
      channel: 'chrome',
      headless: false, 
      ignoreDefaultArgs: ['--disable-extensions', '--enable-automation'], 
      acceptDownloads: true,
      args: [ '--load-extension=#{ext_path}' ],
      proxy: { server: "#{@proxy_addr}:#{@proxy_port}" },
      userAgent: user_agents.sample[:user_agent],
      viewport: {width: @width, height: @height},
      screen: {width: @width, height: @height}
    }
    playwright.chromium.launch_persistent_context('./data/', **launch_param) do |browser|
      page = browser.new_page
      page.goto @url, timeout: 60000
      sleep 1000
    end
  end
```

This is my summary code. But not sure how I can post this issue to https://github.com/microsoft/playwright/issues 
They will not read my ruby code

**Comment by YusukeIwaki** [comment]
You reported 2 unexpected behavior, but the code provided reproduces only the first one (opening 2 tabs).
How can we reproduce the second one (First tab showing automation and the scraper is running on second tab.)?

**Comment by goldenking0412** [comment]
So you don't go to url in the second tab?

**Comment by YusukeIwaki** [comment]
First tab keeps about:blank and autonation runs on the second tab. The second tab is focused.

**Comment by YusukeIwaki** [comment]
This issue is now focused only to opening 2 tabs, which is already reproduced.
If another unexpected behavior is observed and serious for you, please create another issue using bug-report template and provide more information for reproducing the issue.

**Comment by YusukeIwaki** [comment]
playwright-python's example code. It also opens 2 tabs.

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    context = playwright.chromium.launch_persistent_context('./data', headless=False)
    try:
        page = context.new_page()
        page.goto('https://github.com/YusukeIwaki')
        page.click('input[name="q"]')
        page.keyboard.type("playwright")
        with page.expect_navigation():
            page.keyboard.press("Enter")
    finally:
        context.close()
```

As is already described (https://github.com/YusukeIwaki/playwright-ruby-client/issues/115#issuecomment-860211257), this problem is not caused by client (playwright-python or playwright-ruby-client) but caused by playwright driver.
