### ISSUE TITLE
Execution commands page.location("[name='search']").visible? or page.query_selector("[name='search']").visible? ended with Timeout error

### ISSUE THREAD

**Issue by vranky** [YusukeIwaki/playwright-ruby-client#171]
### Step To Reproduce / Observed behavior
require 'playwright'

@playwright_exec = Playwright.create(playwright_cli_executable_path: 'npx playwright')

playwright = @playwright_exec.playwright

browser = playwright.chromium.launch(headless: false, channel: "chrome")
context = browser.new_context
page = context.new_page
page.goto('https://bing.com')
page.location("[name='search']").visible?
![image](https://user-images.githubusercontent.com/10365694/133613590-2356337e-8dd3-4198-8f2f-e653398a9e08.png)

### Expected behavior
True response is occurred.

### Environment

Paste the output of `ruby --version`
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin20]

**Comment by YusukeIwaki** [comment]
`page.location` is not defined. 

The timeout error seems to be caused in RubyMine.

```ruby
require 'playwright'

Playwright.create(playwright_cli_executable_path: 'npx playwright') do |playwright|
  playwright.chromium.launch(headless: false, channel: :chrome) do |browser|
    page = browser.new_page
    page.goto('https://bing.com')
    puts page.location("[name='search']").visible?
  end
end
```

I tried this code and got an error as expected:

```
bing.rb:7:in `block (2 levels) in <main>': undefined method `location' for #<Playwright::Page:0x00007ff119297ea0> (NoMethodError)
Did you mean?  locator
```

And, it works by replacing location with locator.

```
    page.locator("[name='search']").visible?
```

(it returns `false`)

**Comment by vranky** [comment]
Is still doesn't work for me. 
After calling page.locator("[name='search']").visible? I got ->
![image](https://user-images.githubusercontent.com/10365694/133739888-7673f67f-5dd7-46e2-b297-759b6376ae45.png)

**Comment by YusukeIwaki** [comment]
I guess RubyMine's breakpoint suspends all threads (including background messaging thread for communicating with Playwright driver).
https://stackoverflow.com/questions/27784413/how-to-debug-a-multi-threaded-app-in-intellij

Can you choose the option for suspending only the working thread?

**Comment by YusukeIwaki** [comment]
Feel free to reopen if needed.

**Comment by vranky** [comment]
Yes issue was in rubyMine IDE debugger, many thanks.
