### ISSUE TITLE
Error: Unknown scheme for .initialize

### ISSUE THREAD

**Issue by ror-vs** [YusukeIwaki/playwright-ruby-client#220]
### Issue Description
Encounter the error Error: Unknown scheme for .initialize  after debugging it seems failing in launching the browser or connecting to the remote server when running it remotely

- Operating System: Windows
- Operating System: Linux
- Node version 12.18.3
- playwright-ruby-client (1.25.0)

### Expected behavior
It should open the browser 
### Environment
Production
Development
Paste the output of `ruby --version`
ruby 2.6.6

**Below is the code snippet**
![Screenshot from 2022-08-22 17-04-41](https://user-images.githubusercontent.com/92923983/185917060-cedca88a-57ea-45d3-a6e3-b1f2f61c3082.png)

**Comment by YusukeIwaki** [comment]
@ror-vs Hi, sorry for very late response. Which version of Playwright currently do you use? (it is described in package-lock.json or yarn.lock) Is it Playwright 1.25.0-1.25.2?
