### ISSUE TITLE
response.body stucked/freeze 

### ISSUE THREAD

**Issue by shaktik1989** [YusukeIwaki/playwright-ruby-client#227]
### Step To Reproduce / Observed behavior
```
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
    page = browser.new_page
    page.on("response", ->(response) { puts response.body }) //When I call response.body it get freezed and not returning responsebody
    page.goto('https://github.com/YusukeIwaki/playwright-ruby-client/issues')
    sleep(1)  
  end
end

```
### Expected behavior
page.on("response", ->(response) { puts response.body }) This line should print the response of the api on console

### Environment
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
Paste the output of `ruby --version`

**Comment by YusukeIwaki** [comment]
Sorry for inconvenience for a long time. This bug will be fixed in the next release.

**Comment by YusukeIwaki** [comment]
@shaktik1989 https://rubygems.org/gems/playwright-ruby-client/versions/1.28.1 would fix this problem.
