### ISSUE TITLE
Error: sdkLanguage: expected one of (javascript|python|java|csharp) (Playwright::Error)

### ISSUE THREAD

**Issue by janklimo** [YusukeIwaki/playwright-ruby-client#228]
Attempting to run the example script from the readme but it crashes with this error. Looking at the [playwright repo](https://github.com/microsoft/playwright/blob/f7b269d9c6a11b3eb7d2819400112ab238e83d1d/packages/playwright-core/src/server/isomorphic/locatorGenerators.ts#L21), it doesn't seem like passing ruby is allowed as it's being done here:

https://github.com/YusukeIwaki/playwright-ruby-client/blob/9b552ae2e3c263b187755f1670be06eee1193202/lib/playwright/connection.rb#L46

Using `playwright@1.28.0`.

**Comment by davidsf** [comment]
Playwright 1.28.0 released yesterday and it seems the ruby client not support it yet. 

If you want to try, install the previous version with:

```
npm install playwright@1.27.1
```
