### ISSUE TITLE
Add type signatures (RBS)

### ISSUE THREAD

**Issue by navrocky** [YusukeIwaki/playwright-ruby-client#239]
It will be good to have type signatures (RBS) for all classes in this gem for code completion.

https://github.com/ruby/rbs

**Comment by YusukeIwaki** [comment]
@navrocky Could you provide actual code examples to indicate why type definition is wanted?

**Comment by YusukeIwaki** [comment]
@navrocky Initial implementation is added in [1.29.1](https://rubygems.org/gems/playwright-ruby-client/versions/1.29.1). Please try it and let me know the feedback. Thank you.

**Comment by navrocky** [comment]
@YusukeIwaki thanx a lot, i'll try it as soon as i can!

**Comment by navrocky** [comment]
Yeah, code completion in RubyMine started working like a charm. Thank you!
