### ISSUE TITLE
How can I set --use-gl=egl?

### ISSUE THREAD

**Issue by mhenrixon** [YusukeIwaki/playwright-ruby-client#247]
### Usecase / What to achieve

I want to improve performance

### Question

How would I provide `--use-gl=egl` to the args tp the playwright binary? Read the following; https://michelkraemer.com/enable-gpu-for-slow-playwright-tests-in-headless-mode/

It seems on my M2 Max it is as fast to round headless as in the browser visible ;) 

```ruby
DRIVER_OPTS = {
  playwright_cli_executable_path: "./node_modules/.bin/playwright",
  browser_type: BROWSER,
  headless: HEADLESS,
  slowMo: 60,
  args: %w[--use-gl=egl],
}.freeze

Capybara.register_driver(:playwright) do |app|
  Capybara::Playwright::Driver.new(app, **DRIVER_OPTS)
end
```

**Comment by YusukeIwaki** [comment]
@mhenrixon Hi, sorry for my late response.

In my observation, older version of playwright (v1.25) respect `--use-gl=egl`, however current version of Playwright (v1.32) doesn't. Probably it's up to the version of Chromium.

playwright-ruby-client and capybara-playwright-driver just pass `args: ['--use-gl=egl']` to Playwright server and it works on Playwright 1.25 and not work on Playwright 1.32.

Could you submit an issue into Playwright (JS) if it is an unexpected behavior for you?

**Comment by mhenrixon** [comment]
Errm. I just updated playwright-ruby-client, and suddenly my test time went from 1 minute 20 seconds to 37 seconds.

I have no idea if that's the reason or something else, but I'll take it. Someone, somewhere, fixed something.
