### ISSUE TITLE
Unclear Instruction in Readme: "And set playwright_cli_executable_path: './node_modules/.bin/playwright'"

### ISSUE THREAD

**Issue by mitchmeyer1** [YusukeIwaki/playwright-ruby-client#252]
In the readme the instruction after installing the npm package for playwright says:
`And set playwright_cli_executable_path: './node_modules/.bin/playwright'`

What does this mean? set where? A system Env var? in some document? What is this referring to?

Thanks!

**Comment by YusukeIwaki** [comment]
Please refer this guide. https://playwright-ruby-client.vercel.app/docs/article/getting_started
