### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cferraz-es** [YusukeIwaki/playwright-ruby-client#265]
### Usecase / What to achieve
Trying to install the client

### Question
When I run the first command `gem install 'playwright-ruby-client'`

I get this error:
`ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command playwright-ruby-client`

Am I missing anything?

Describe current status of your trial if possible.
Concrete description would be helpful for receiving more accurate solution.

**Comment by YusukeIwaki** [comment]
```
$ gem install 'playwright-ruby-client'
Fetching playwright-ruby-client-1.37.1.gem
Successfully installed playwright-ruby-client-1.37.1
Parsing documentation for playwright-ruby-client-1.37.1
Installing ri documentation for playwright-ruby-client-1.37.1
Done installing documentation for playwright-ruby-client after 1 seconds
1 gem installed

A new release of RubyGems is available: 3.4.1 → 3.4.19!
Run `gem update --system 3.4.19` to update your installation.
```

If you use Windows, please try `gem install playwright-ruby-client` (without quotation)
