### ISSUE TITLE
Update to Playwright 1.48.0

### ISSUE THREAD

**Issue by manuelmeurer** [YusukeIwaki/playwright-ruby-client#308]
Playwright 1.48.0 was just released: https://github.com/microsoft/playwright/releases/tag/v1.48.0
What is the process to update the Playwright version in this gem?
Happy to take a stab at a PR for it!

**Comment by manuelmeurer** [comment]
1.48.2 is out! :)

@Yusukelwaki Could you tell me your process of updating this gem to support a new Playwright version?
Maybe I or other contributors could do it in the future.

**Comment by YusukeIwaki** [comment]
Thank you for your suggestion. On every update, I execute the steps below:

* Execute `bundle exec ruby development/generate_api.rb`
* Update lib/playwright/version.rb
* Observe pull request in playwright-python like this: https://github.com/microsoft/playwright-python/pull/2584/files and update implementation.
