### ISSUE TITLE
Are there any plans to update the API Coverage docs?

### ISSUE THREAD

**Issue by saku888** [YusukeIwaki/playwright-ruby-client#318]
### Usecase / What to achieve
https://playwright-ruby-client.vercel.app/docs/article/api_coverage
I would like specific explanations such as usage and arguments on this page.
Once the documentation is complete, it will be easier to implement and more people will use it.

### Question
Are there any plans to make this page more detailed?
Or if you prepare a document, could you please reflect it?

**Comment by YusukeIwaki** [comment]
API documentation is here: https://playwright-ruby-client.vercel.app/docs/api/playwright

This documentation is automarically generated by `developmenr/generate_api.rb`. The source of the document is in `microsoft/playwright` repository in YAML formatted, and this generate_api.rb script parses the YAML doc for python and convert it into Ruby example codes internally.

**Comment by saku888** [comment]
thank you !!
