### ISSUE TITLE
Using "check" on radiobutton element leads to ArgumentError: unknown keyword: position

### ISSUE THREAD

**Issue by rammpeter** [YusukeIwaki/playwright-ruby-client#63]
### Step To Reproduce / Observed behavior
 page.query_selector("#database_modus_host").check
raises "ArgumentError: unknown keyword: position"

It calls
playwright-ruby-client-0.5.2/lib/playwright_api/element_handle.rb:134:in `check'
which calls 
playwright-ruby-client-0.5.2/lib/playwright/channel_owners/element_handle.rb:234:in `check'
with parameter "position:" which is not defined in element_handle.rb:234

### Expected behavior
selecting radio button without error 

### Environment

Paste the output of `ruby --version`
jruby-9.2.17.0

Workaround exists in still using click instead of check.

**Comment by YusukeIwaki** [comment]
https://github.com/YusukeIwaki/playwright-ruby-client/pull/55

check/unckeck in ElementHandle should be changed in this PR.

**Comment by YusukeIwaki** [comment]
I will fix this

**Comment by YusukeIwaki** [comment]
@rammpeter Thank you for the bug report, and sorry for inconvinience.
This issue is fixed on 0.5.3. Could you try it?

**Comment by rammpeter** [comment]
I've tried the issue, works now. Thank you.
