### ISSUE TITLE
How to run script on opening new page?

### ISSUE THREAD

**Issue by goldenking0412** [YusukeIwaki/playwright-ruby-client#95]
```ruby
driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
  "source": """
    Object.defineProperty(navigator, 'webdriver', {
      get: () => undefined
    })
  """
})
```

Like above, I want to run some script on new document. How can I do this?
Above ruby script is for selenium.

**Comment by YusukeIwaki** [comment]
How about this method?
https://playwright-ruby-client.vercel.app/docs/api/browser_context#add_init_script

**Comment by goldenking0412** [comment]
Got it, thanks
Do we have wait element method?

**Comment by YusukeIwaki** [comment]
Probably you can use this
https://playwright-ruby-client.vercel.app/docs/api/page#wait_for_selector

**Comment by goldenking0412** [comment]
Thanks

```ruby
Playwright.create(playwright_cli_executable_path: 'npx playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
    page = browser.new_page
    page.goto('https://github.com/YusukeIwaki')
    # I can not write much script scraping certain page
  end
end
```

How can I organize bunch of scraping script here outside the Playwright.create scope?

**Comment by YusukeIwaki** [comment]
We can use `Playwright.create` to create PlaywrightExecution and `PlaywrightExecution#stop`, instead of `Playwright.create do ... end`
https://playwright-ruby-client.vercel.app/docs/article/guides/launch_browser#define-startend-of-the-playwright-session-separately-without-block

**Comment by YusukeIwaki** [comment]
Playwright Official documentation introduces many useful features. Please take a look at the documentation before using this Gem.
https://playwright.dev/docs/next/intro

This Gem is just a Ruby port of Playwright. Most features are common with TypeScript or Python's library.
Feel free to post a new issue when you find playwright-ruby-client specific problems or questions. Thank you.
